<Project>
  <Import Project="..\Directory.Build.targets" />

  <PropertyGroup>
    <NETFrameworkReferenceAssemblyTFM>net48</NETFrameworkReferenceAssemblyTFM>
    <NetFxRefPath>$([MSBuild]::NormalizeDirectory('$(NuGetPackageRoot)', 'microsoft.netframework.referenceassemblies.$(NETFrameworkReferenceAssemblyTFM)', '$(MicrosoftNETFrameworkReferenceAssembliesLatestPackageVersion)', 'build', '.NETFramework', 'v4.8'))</NetFxRefPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'netstandard'">
    <PackageDownload Include="Microsoft.NETFramework.ReferenceAssemblies.$(NETFrameworkReferenceAssemblyTFM)"
                     Version="[$(MicrosoftNETFrameworkReferenceAssembliesLatestPackageVersion)]" />
    <ResolvedMatchingContract Include="$(NetFxRefPath)$(MSBuildProjectName).dll" />
  </ItemGroup>
</Project>
